# core/exchange/base.py
from typing import Protocol
from ..models import MarketState, InventoryState, Order, Side, ProductModel


class ExchangeClient(Protocol):
    name: str

    async def connect_ws(self) -> None: ...
    async def close(self) -> None: ...

    async def subscribe_orderbook(self, symbol: str) -> None: ...
    async def get_market_state(self, symbol: str) -> MarketState: ...

    async def get_inventory(self, symbol: str) -> InventoryState: ...
    async def get_open_orders(self, symbol: str) -> list[Order]: ...

    async def place_limit_order(
        self,
        symbol: str,
        side: Side,
        price: float,
        amount: float,
        post_only: bool = True,
        reduce_only: bool = False,
        client_order_id: str | None = None,
    ) -> Order: ...

    async def cancel_order(self, symbol: str, order_id: str) -> None: ...
    async def cancel_all_symbol(self, symbol: str) -> None: ...

    def get_product_model(self, symbol: str) -> ProductModel: ...
    def get_tick_size(self, symbol: str) -> float: ...
    def get_min_order_size(self, symbol: str) -> float: ...
